### ISSUE TITLE
Reddit login credentials in version control

### ISSUE THREAD

**Issue by Andygmb** [jakeingit/Showerthoughts-Reddit-to-Twitter-Bot#1]
https://github.com/jakeingit/Showerthoughts-Reddit-to-Twitter-Bot/blob/master/practice2.py#L14-L17

https://github.com/jakeingit/Showerthoughts-Reddit-to-Twitter-Bot/blob/master/practice.py#L14-L21

You need to change your reddit password and revoke all those access keys now. Like really, right now.

**Comment by jakeingit** [comment]
thanks. I knew I was risking it when I put it up, but didnt realize anyone would really care about some random bot.

Thanks for the hearty laugh.

**Comment by Andygmb** [comment]
There's always someone out there looking for these kinds of things - never assume you're safe by being a small fish in a big pond :smiley: 

http://wptavern.com/ryan-hellyers-aws-nightmare-leaked-access-keys-result-in-a-6000-bill-overnight

**Comment by pensivearchitect** [comment]
its considered best practice to store secrets in an environment variable (eg `os.environ['MY_SUPER_SEKRIT_PASSWORD']`)
