### ISSUE TITLE
Credentials still in history

### ISSUE THREAD

**Issue by Echohawkdown** [jakeingit/Showerthoughts-Reddit-to-Twitter-Bot#2]
https://github.com/jakeingit/Showerthoughts-Reddit-to-Twitter-Bot/commit/00e60e6adec55977942789018c834ef68f57b823#diff-bc300c4483b7f62571671468986e1b6eR14

https://github.com/jakeingit/Showerthoughts-Reddit-to-Twitter-Bot/commit/00e60e6adec55977942789018c834ef68f57b823#diff-bc300c4483b7f62571671468986e1b6eR14

**Comment by jakeingit** [comment]
thanks for noticing.

**Comment by jakeingit** [comment]
So looking into this, Twitter lets you reset both of the authentication secrets and keys to their API. While this repository is public, it wont ever work for anything since I reset it when I last committed the changes.
